name = "Create The Network"
author = "Otterlord"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e76ea23d2f119c3d02a2e49ecf85629cf82b7e1027259fc26d8056c1edbb450f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.99"
